name: Test DevContainer Features

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        features:
          - git-config
    steps:
      - uses: actions/checkout@v3

      - name: Install DevContainer CLI
        run: npm install -g @devcontainers/cli

      - name: Validate Feature Metadata
        run: |
          echo "Validating ${{ matrix.features }}..."
          devcontainer features validate src/${{ matrix.features }}

      - name: Run Tests
        run: |
          echo "Testing ${{ matrix.features }}..."
          devcontainer features test \
            --features src/${{ matrix.features }} \
            --base-image ubuntu:latest

  test-all-scenarios:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3

      - name: Install DevContainer CLI
        run: npm install -g @devcontainers/cli

      - name: Test All Scenarios
        run: |
          echo "Running all test scenarios..."
          devcontainer features test --features src

  validate-structure:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check File Permissions
        run: |
          echo "Checking install.sh permissions..."
          for feature in src/*/; do
            if [ -f "$feature/install.sh" ]; then
              if [ ! -x "$feature/install.sh" ]; then
                echo "ERROR: $feature/install.sh is not executable"
                exit 1
              fi
            fi
          done

      - name: Validate JSON Files
        run: |
          echo "Validating JSON files..."
          for file in src/*/devcontainer-feature.json test/*/scenarios.json; do
            if [ -f "$file" ]; then
              echo "Checking $file..."
              jq empty "$file" || exit 1
            fi
          done
